openapi: 3.0.0
info:
  description: Basic project with Flask , Gunicorn, Connexion and OpenApi 3
  version: 1.0.0
  title: Connexion example
  contact:
    email: vikatawin@gmail.com
tags:
  - name: alive
    description: Keepalive
paths:
  /ping:
    get:
      tags:
        - alive
      summary: Api keepalive
      description: Api keepalive
      operationId: source.controllers.heartBeatController.isAlive
      responses:
        "200":
          description: is alive
servers:
  - url: http://0.0.0.0:8081/v1/source